version: "3.3"
services:
  data_dashboard_web:
    build: .
    volumes:
      - .:/dashboard
    ports:
      - "3000:3000"
    links:
      - data_dashboard_db
    env_file:
      - secrets.env
  data_dashboard_db:
    image: postgres:9.4
    environment:
       POSTGRES_DB: data_dashboard_production
       POSTGRES_USER: data_dashboard
       POSTGRES_PASSWORD: password
    ports:
      - "5432"

networks:
  default:
    external:
      name: ddboard-deploy
