default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: data_dashboard_development
test:
  <<: *default
  database: data_dashboard_test
production:
  <<: *default
  database: data_dashboard_production
  username: data_dashboard
  password: password
  host: postgres(data_dashboard_db)
